In [2]:
import pandas as pd
import joblib

In [12]:
df_test=pd.read_csv("Testing.csv")
df_train=pd.read_csv("Training.csv").drop(columns=["Unnamed: 133"])

In [14]:
df_test.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction

In [15]:
X_train = df_train.drop('prognosis', axis=1)
X_test = df_test.drop('prognosis', axis=1)

y_train = df_train['prognosis']
y_test = df_test['prognosis']

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
dtree_model= DecisionTreeClassifier()

In [18]:
dtree_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [19]:
predictions= dtree_model.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score, classification_report

print(classification_report(y_test, predictions))

accuracy = accuracy_score(y_test, predictions)
print(f"Model Doğruluk Oranı: %{accuracy * 100:.2f}")

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00         1
                                   AIDS       1.00      1.00      1.00         1
                                   Acne       1.00      1.00      1.00         1
                    Alcoholic hepatitis       1.00      1.00      1.00         1
                                Allergy       1.00      1.00      1.00         1
                              Arthritis       1.00      1.00      1.00         1
                       Bronchial Asthma       1.00      1.00      1.00         1
                   Cervical spondylosis       1.00      1.00      1.00         1
                            Chicken pox       1.00      1.00      1.00         1
                    Chronic cholestasis       1.00      1.00      1.00         1
                            Common Cold       1.00      1.00      1.00         1
                                 Dengue       1.00      1.00      1.00         1
                              Diabetes        1.00      1.00      1.00         1
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00         1
                          Drug Reaction       1.00      1.00      1.00         1
                       Fungal infection       1.00      0.50      0.67         2
                                   GERD       1.00      1.00      1.00         1
                        Gastroenteritis       1.00      1.00      1.00         1
                           Heart attack       1.00      1.00      1.00         1
                            Hepatitis B       1.00      1.00      1.00         1
                            Hepatitis C       0.50      1.00      0.67         1
                            Hepatitis D       1.00      1.00      1.00         1
                            Hepatitis E       1.00      1.00      1.00         1
                          Hypertension        1.00      1.00      1.00         1
                        Hyperthyroidism       1.00      1.00      1.00         1
                           Hypoglycemia       1.00      1.00      1.00         1
                         Hypothyroidism       1.00      1.00      1.00         1
                               Impetigo       1.00      1.00      1.00         1
                               Jaundice       1.00      1.00      1.00         1
                                Malaria       1.00      1.00      1.00         1
                               Migraine       1.00      1.00      1.00         1
                        Osteoarthristis       1.00      1.00      1.00         1
           Paralysis (brain hemorrhage)       1.00      1.00      1.00         1
                    Peptic ulcer diseae       1.00      1.00      1.00         1
                              Pneumonia       1.00      1.00      1.00         1
                              Psoriasis       1.00      1.00      1.00         1
                           Tuberculosis       1.00      1.00      1.00         1
                                Typhoid       1.00      1.00      1.00         1
                Urinary tract infection       1.00      1.00      1.00         1
                         Varicose veins       1.00      1.00      1.00         1
                            hepatitis A       1.00      1.00      1.00         1

                               accuracy                           0.98        42
                              macro avg       0.99      0.99      0.98        42
                           weighted avg       0.99      0.98      0.98        42

Model Doğruluk Oranı: %97.62

In [28]:
joblib.dump(dtree_model, 'hastalik_tahmin_modeli.pkl')

joblib.dump(X_train.columns.tolist(), 'semptom_listesi.pkl')

print("Model ve semptom listesi başarıyla .pkl olarak kaydedildi!")

Model ve semptom listesi başarıyla .pkl olarak kaydedildi!

In [4]:
dosya_oku1=pd.read_pickle('semptom_listesi.pkl')
dosya_oku

['itching',
 'skin_rash',
 'nodal_skin_eruptions',
 'continuous_sneezing',
 'shivering',
 'chills',
 'joint_pain',
 'stomach_pain',
 'acidity',
 'ulcers_on_tongue',
 'muscle_wasting',
 'vomiting',
 'burning_micturition',
 'spotting_ urination',
 'fatigue',
 'weight_gain',
 'anxiety',
 'cold_hands_and_feets',
 'mood_swings',
 'weight_loss',
 'restlessness',
 'lethargy',
 'patches_in_throat',
 'irregular_sugar_level',
 'cough',
 'high_fever',
 'sunken_eyes',
 'breathlessness',
 'sweating',
 'dehydration',
 'indigestion',
 'headache',
 'yellowish_skin',
 'dark_urine',
 'nausea',
 'loss_of_appetite',
 'pain_behind_the_eyes',
 'back_pain',
 'constipation',
 'abdominal_pain',
 'diarrhoea',
 'mild_fever',
 'yellow_urine',
 'yellowing_of_eyes',
 'acute_liver_failure',
 'fluid_overload',
 'swelling_of_stomach',
 'swelled_lymph_nodes',
 'malaise',
 'blurred_and_distorted_vision',
 'phlegm',
 'throat_irritation',
 'redness_of_eyes',
 'sinus_pressure',
 'runny_nose',
 'congestion',
 'chest_pain',
 'weakness_in_limbs',
 'fast_heart_rate',
 'pain_during_bowel_movements',
 'pain_in_anal_region',
 'bloody_stool',
 'irritation_in_anus',
 'neck_pain',
 'dizziness',
 'cramps',
 'bruising',
 'obesity',
 'swollen_legs',
 'swollen_blood_vessels',
 'puffy_face_and_eyes',
 'enlarged_thyroid',
 'brittle_nails',
 'swollen_extremeties',
 'excessive_hunger',
 'extra_marital_contacts',
 'drying_and_tingling_lips',
 'slurred_speech',
 'knee_pain',
 'hip_joint_pain',
 'muscle_weakness',
 'stiff_neck',
 'swelling_joints',
 'movement_stiffness',
 'spinning_movements',
 'loss_of_balance',
 'unsteadiness',
 'weakness_of_one_body_side',
 'loss_of_smell',
 'bladder_discomfort',
 'foul_smell_of urine',
 'continuous_feel_of_urine',
 'passage_of_gases',
 'internal_itching',
 'toxic_look_(typhos)',
 'depression',
 'irritability',
 'muscle_pain',
 'altered_sensorium',
 'red_spots_over_body',
 'belly_pain',
 'abnormal_menstruation',
 'dischromic _patches',
 'watering_from_eyes',
 'increased_appetite',
 'polyuria',
 'family_history',
 'mucoid_sputum',
 'rusty_sputum',
 'lack_of_concentration',
 'visual_disturbances',
 'receiving_blood_transfusion',
 'receiving_unsterile_injections',
 'coma',
 'stomach_bleeding',
 'distention_of_abdomen',
 'history_of_alcohol_consumption',
 'fluid_overload.1',
 'blood_in_sputum',
 'prominent_veins_on_calf',
 'palpitations',
 'painful_walking',
 'pus_filled_pimples',
 'blackheads',
 'scurring',
 'skin_peeling',
 'silver_like_dusting',
 'small_dents_in_nails',
 'inflammatory_nails',
 'blister',
 'red_sore_around_nose',
 'yellow_crust_ooze']

In [7]:
dosya_oku2=pd.read_pickle('hastalik_tahmin_modeli.pkl')
dosya_oku2

array(['itching', 'skin_rash', 'nodal_skin_eruptions',
       'continuous_sneezing', 'shivering', 'chills', 'joint_pain',
       'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting',
       'vomiting', 'burning_micturition', 'spotting_ urination',
       'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets',
       'mood_swings', 'weight_loss', 'restlessness', 'lethargy',
       'patches_in_throat', 'irregular_sugar_level', 'cough',
       'high_fever', 'sunken_eyes', 'breathlessness', 'sweating',
       'dehydration', 'indigestion', 'headache', 'yellowish_skin',
       'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes',
       'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea',
       'mild_fever', 'yellow_urine', 'yellowing_of_eyes',
       'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach',
       'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision',
       'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure',
       'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs',
       'fast_heart_rate', 'pain_during_bowel_movements',
       'pain_in_anal_region', 'bloody_stool', 'irritation_in_anus',
       'neck_pain', 'dizziness', 'cramps', 'bruising', 'obesity',
       'swollen_legs', 'swollen_blood_vessels', 'puffy_face_and_eyes',
       'enlarged_thyroid', 'brittle_nails', 'swollen_extremeties',
       'excessive_hunger', 'extra_marital_contacts',
       'drying_and_tingling_lips', 'slurred_speech', 'knee_pain',
       'hip_joint_pain', 'muscle_weakness', 'stiff_neck',
       'swelling_joints', 'movement_stiffness', 'spinning_movements',
       'loss_of_balance', 'unsteadiness', 'weakness_of_one_body_side',
       'loss_of_smell', 'bladder_discomfort', 'foul_smell_of urine',
       'continuous_feel_of_urine', 'passage_of_gases', 'internal_itching',
       'toxic_look_(typhos)', 'depression', 'irritability', 'muscle_pain',
       'altered_sensorium', 'red_spots_over_body', 'belly_pain',
       'abnormal_menstruation', 'dischromic _patches',
       'watering_from_eyes', 'increased_appetite', 'polyuria',
       'family_history', 'mucoid_sputum', 'rusty_sputum',
       'lack_of_concentration', 'visual_disturbances',
       'receiving_blood_transfusion', 'receiving_unsterile_injections',
       'coma', 'stomach_bleeding', 'distention_of_abdomen',
       'history_of_alcohol_consumption', 'fluid_overload.1',
       'blood_in_sputum', 'prominent_veins_on_calf', 'palpitations',
       'painful_walking', 'pus_filled_pimples', 'blackheads', 'scurring',
       'skin_peeling', 'silver_like_dusting', 'small_dents_in_nails',
       'inflammatory_nails', 'blister', 'red_sore_around_nose',
       'yellow_crust_ooze'], dtype=object)

In [30]:
from mlxtend.frequent_patterns import apriori, association_rules

frequent_itemsets = apriori(X_train, min_support=0.05, use_colnames=True)

rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

top_rules = rules.sort_values(by='confidence', ascending=False)

top_rules.to_csv('birliktelik_kurallari.csv', index=False)

print("Apriori ile Birliktelik Kuralları başarıyla hesaplandı ve 'birliktelik_kurallari.csv' olarak kaydedildi!")

top_rules.head(10)

C:\Anaconda\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Apriori ile Birliktelik Kuralları başarıyla hesaplandı ve 'birliktelik_kurallari.csv' olarak kaydedildi!

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1122,"(phlegm, malaise)",(chest_pain),0.069512,0.141463,0.069512,1.0,7.068966,1.0,0.059679,inf,0.922674,0.491379,1.0,0.745690
1224,"(fatigue, chills, cough)",(chest_pain),0.062195,0.141463,0.062195,1.0,7.068966,1.0,0.053397,inf,0.915475,0.439655,1.0,0.719828
5288,"(fatigue, high_fever, phlegm, malaise)",(chest_pain),0.062195,0.141463,0.062195,1.0,7.068966,1.0,0.053397,inf,0.915475,0.439655,1.0,0.719828
1394,"(chills, cough, malaise)",(chest_pain),0.063415,0.141463,0.063415,1.0,7.068966,1.0,0.054444,inf,0.916667,0.448276,1.0,0.724138
1364,"(high_fever, chills, cough)",(chest_pain),0.062195,0.141463,0.062195,1.0,7.068966,1.0,0.053397,inf,0.915475,0.439655,1.0,0.719828
1322,"(fatigue, chills, phlegm)",(chest_pain),0.064634,0.141463,0.064634,1.0,7.068966,1.0,0.055491,inf,0.917862,0.456897,1.0,0.728448
7940,"(high_fever, malaise, chills, phlegm, fatigue,...",(chest_pain),0.054878,0.141463,0.054878,1.0,7.068966,1.0,0.047115,inf,0.908387,0.387931,1.0,0.693966
5258,"(fatigue, phlegm, cough, malaise)",(chest_pain),0.062195,0.141463,0.062195,1.0,7.068966,1.0,0.053397,inf,0.915475,0.439655,1.0,0.719828
5228,"(fatigue, high_fever, phlegm, cough)",(chest_pain),0.060976,0.141463,0.060976,1.0,7.068966,1.0,0.052350,inf,0.914286,0.431034,1.0,0.715517
1406,"(chills, phlegm, cough)",(chest_pain),0.064634,0.141463,0.064634,1.0,7.068966,1.0,0.055491,inf,0.917862,0.456897,1.0,0.728448